### ISSUE TITLE
Emergency illumination room

### ISSUE THREAD

**Issue by jowie94** [NeebulaGames/SpacePlayground#3]
Using a simple corridor of the spaceship, implement a room using the *emergency mode* illumination

**Comment by miriamcastellon** [comment]
WIP

![emergencymodeillumination](https://cloud.githubusercontent.com/assets/23148975/22629444/9630c1a8-ebe6-11e6-81fa-3a9ff59f376e.jpg)

**Comment by Shandy92** [comment]
**Final result**

#issuenumber3
![emergency](https://cloud.githubusercontent.com/assets/23011739/22669572/80040bee-ecc5-11e6-9150-e082d8a738b4.PNG)
